default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: badminton_league_development
test:
  <<: *default
  database: badminton_league_test
production:
  primary: &primary_production
    <<: *default
    database: badminton_league_production
    username: badminton_league
    password: <%= ENV["BADMINTON_LEAGUE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: badminton_league_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: badminton_league_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: badminton_league_production_cable
    migrations_paths: db/cable_migrate
